### ISSUE TITLE
Advance rekon - Dropbox token 

### ISSUE THREAD

**Issue by cduverne** [I-Am-Jakoby/Flipper-Zero-BadUSB#1]
Hey there,

The dropbox access token is quite short-lived,
Is there a way to implement a refresh mechanism within the script ?

Cheers
CyD

**Comment by I-Am-Jakoby** [comment]
Unfortunately no. 
That was a recent change. I still have some tokens that last forever.
But I'm working on some other tutorials for methods that don't expire. 
But it would require having a dns server or something similar

**Comment by cduverne** [comment]
Hey,

Thanks for your swift reply.
Maybe, we could use another file sharing solution. Ie. Mega, or something ?

Cheers
CyD

Le dim. 31 juil. 2022, 22:44, I-Am-Jakoby ***@***.***> a
écrit :
