### ISSUE TITLE
please can you clarify

### ISSUE THREAD

**Issue by cjpatters** [I-Am-Jakoby/Flipper-Zero-BadUSB#10]
hi I seen there is a bad usb script called we found you. I'm unsure how this script operates though, surely you already know where the person is if youve gained physical access to their PC with a bad usb, so why would you need a location ping? I'm just genuinely unsure how this is utilised, any info would be great help.

hope to hear from you soon, 
thanks in advance.

**Comment by I-Am-Jakoby** [comment]
so you do not have to leave the device plugged into their system for this to work.
You can execute this script and take out the device and walk away
the person might come back 2 hours later and it will execute when they move their mouse 
this is just a prank payload 

however the file itself can be used with a device at all. sending it to a scammer for example

**Comment by neo1000101** [comment]
Hello, I have trouble with the ADV-Recon script. I am trying to run it via Bad-USB on the Flipper Device. I can't seem to find the correct way of linking my dropbox in the .txt file so when I run the script nothing happens. I've read it several times the read.me and I still don't find a way to make it work so I am reaching out for your help:)

Also, a video on your script and the flipper would be very nice and appreciated!

Thank you and keep the good work

**Comment by I-Am-Jakoby** [comment]
So I just over the last few days updated every single script in this repo 
You now do not have to modify the .ps1 file or host it somewhere yourself 
if you look at the text file there is a variable called `$db` and if you put your token in there that is all you need to do
Everything else is taken care of now. 

if you have anymore questions on the other feel free to come through the discord
