### ISSUE TITLE
Advanced Recon Upload Problems

### ISSUE THREAD

**Issue by TheGreenProphet** [I-Am-Jakoby/Flipper-Zero-BadUSB#2]
Hey Jakoby,

first of all thanks for the nice work and keep it up.

Second I got a problem with the script not uploading the file to my dropbox. Found your Youtube tutorial as well and that script with the same Access Key worked just fine, so I don't know what I'm missing.

Would be really happy if you could help me.

Alle the best.

Max

**Comment by I-Am-Jakoby** [comment]
I'm flying back home from defcon tomorrow. When I get back if you want to get in touch with me via discord or something I can sit with you and we can work out what the issue is. You are really appreciated

**Comment by TheGreenProphet** [comment]
Thanks for your fast response. Sounds like a nice idea. My discord name is TheGreenProphet#8432 See you there and have a nice defcon and safe flight.
