### ISSUE TITLE
RickRoll payload video not loading (blank window)

### ISSUE THREAD

**Issue by oil3r** [I-Am-Jakoby/Flipper-Zero-BadUSB#6]
Hi,

I'm trying to run the rickroll payload. I get a window (powershell video player) but its empty, the video is not showing up. I checked the code but I don't know the problem. I see the mp4 video is downloaded in my temp folder. I did not change the code. I'm testing on Win10

**Comment by Habibisemtex** [comment]
Make a new txt 
Copy the line put delay500 befor enter and this thing work I has the same problem

**Comment by I-Am-Jakoby** [comment]
> 

thank you, i went ahead and made that adjustment
